
P0_Frame_1
        ;draw from top to bottom
        .byte #%00000000 ; pre-amble
        .byte #%01111100 ;0
        .byte #%01111110 ;1
        .byte #%01101000 ;2
        .byte #%01111100 ;3
        .byte #%00111100 ;4
        .byte #%00000000 ;5
        .byte #%01111000 ;6 
        .byte #%10111101 ;7
        .byte #%10111110 ;8
        .byte #%01011100 ;9
        .byte #%01111000 ;10
        .byte #%00000000 ;12
        .byte #%01110110 ;11
        .byte #%00000000 ;12
P0_Color
        ;draw from top to bottom
        .byte #CONS_COLOR_PINK ;0
        .byte #CONS_COLOR_PINK ;0
        .byte #CONS_COLOR_PINK ;1
        .byte #CONS_COLOR_CHART ;2
        .byte #CONS_COLOR_CHART ;3
        .byte #CONS_COLOR_CHART ;4
        .byte #CONS_COLOR_PINK ;5
        .byte #CONS_COLOR_PINK ;6 
        .byte #CONS_COLOR_PINK ;7
        .byte #CONS_COLOR_PINK ;8
        .byte #CONS_COLOR_PINK ;9
        .byte #CONS_COLOR_PINK ;10
        .byte #CONS_COLOR_PINK ;12
        .byte #CONS_COLOR_CHART ;11
        .byte #CONS_COLOR_CHART ;12