CONS_COLOR_BLACK  EQU $00
CONS_COLOR_LGREY  EQU #04
CONS_COLOR_GREY_C EQU $0C
CONS_COLOR_GREY_7 EQU $07
CONS_COLOR_GREY   EQU $02
CONS_COLOR_WHITE  EQU $0E

CONS_COLOR_RED    EQU $46
CONS_COLOR_ORANGE EQU $38
CONS_COLOR_YELLOW EQU $1E
CONS_COLOR_GREEN  EQU $C6
CONS_COLOR_BLUE   EQU $A6
CONS_COLOR_PURPLE EQU $64

CONS_COLOR_PINK   EQU $3C
CONS_COLOR_TEAL   EQU $8D
CONS_COLOR_CHART  EQU $CA